name: PipelineTest

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build
        run: mvn -B package --file pom.xml
        working-directory: ${{ github.workspace }}
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy
        run: |
          whoami
          cp target/*.war /usr/share/tomcat/webapps
          echo DONE
        working-directory: ${{ github.workspace }}
