name: PipelineTest

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build
        run: mvn -B package --file pom.xml
        working-directory: ${{ github.workspace }}

      - name: savewar
        uses: actions/upload-artifact@v4
        with:
          name: petclinic
          path: target/*.war
  
  test:
    runs-on: self-hosted
    needs: build
    steps:    
    - name: JMeter Test run
      run: |
        pwd
        /apache-jmeter-5.6.3/bin/jmeter -n -t /jmetertest/FirstJMeter.jmx -l result.jtl
     
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error
  
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: downloadwar
        uses: actions/download-artifact@v4
        with:
          name: petclinic
          path: /tmp

      - name: deploy
        run: |
          pwd
          cp /tmp/petclinic.war /usr/share/tomcat/webapps
        working-directory: ${{ github.workspace }}
