name: PipelineTest

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build
        run: mvn -B package --file pom.xml
        working-directory: ${{ github.workspace }}

      - name: savewar
        uses: actions/upload-artifact@v4
        with:
          name: petclinic
          path: target/*.war
  test_1:
    runs-on: self-hosted
    needs: build
    steps:    
    - name: Selenium Test run
      run: |
        cd tests
        pytest test_websitebasic.py --html=seleniumreport.html
    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: selenium-results
        path: /home/gyan/Documents/cicdgithub/tests/*.html
        if-no-files-found: error
  
  test_2:
    runs-on: self-hosted
    needs: test_1
    steps:    
    - name: JMeter Test run
      run: /home/gyan/Downloads/apache-jmeter-5.6.3/bin/jmeter -n -t /home/gyan/Documents/cicdgithub/tests/FirstJMeter.jmx -l /home/gyan/Documents/cicdgithub/tests/result.jtl
     
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: /home/gyan/Documents/cicdgithub/tests/*.jtl
        if-no-files-found: error
  
 
  deploy:
    runs-on: self-hosted
    needs: test_2
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: downloadwar
        uses: actions/download-artifact@v4
        with:
          name: petclinic
          path: /tmp

      - name: deploy
        run: cp /tmp/petclinic.war /usr/share/tomcat/webapps
        working-directory: ${{ github.workspace }}
