name: PipelineTest

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build
        run: mvn -B package --file pom.xml
        working-directory: ${{ github.workspace }}
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: debug
        run: |
          pwd
          ls
          whoami
          echo ${{ github.workspace }}

      - name: deploy
        run: |
          cp home/gyan/Downloads/actions-runner/_work/cicdgithub/cicdgithub/target/petclinic.war /usr/share/tomcat/webapps
        working-directory: ${{ github.workspace }}
